package com.telecomjs.beans;

import java.io.Serializable;
import java.util.Date;

public class EopAppOnlineBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.ONLINE_ID
     *
     * @mbggenerated
     */
    private Long onlineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.APP_ID
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.APIKEY
     *
     * @mbggenerated
     */
    private String apikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.APP_SECRET
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.TOKEN
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.TOKEN_STAMP
     *
     * @mbggenerated
     */
    private String tokenStamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.CLIENT_IP
     *
     * @mbggenerated
     */
    private String clientIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP_ONLINE.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.ONLINE_ID
     *
     * @return the value of EOP_APP_ONLINE.ONLINE_ID
     *
     * @mbggenerated
     */
    public Long getOnlineId() {
        return onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.ONLINE_ID
     *
     * @param onlineId the value for EOP_APP_ONLINE.ONLINE_ID
     *
     * @mbggenerated
     */
    public void setOnlineId(Long onlineId) {
        this.onlineId = onlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.APP_ID
     *
     * @return the value of EOP_APP_ONLINE.APP_ID
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.APP_ID
     *
     * @param appId the value for EOP_APP_ONLINE.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.APIKEY
     *
     * @return the value of EOP_APP_ONLINE.APIKEY
     *
     * @mbggenerated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.APIKEY
     *
     * @param apikey the value for EOP_APP_ONLINE.APIKEY
     *
     * @mbggenerated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.APP_SECRET
     *
     * @return the value of EOP_APP_ONLINE.APP_SECRET
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.APP_SECRET
     *
     * @param appSecret the value for EOP_APP_ONLINE.APP_SECRET
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.TOKEN
     *
     * @return the value of EOP_APP_ONLINE.TOKEN
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.TOKEN
     *
     * @param token the value for EOP_APP_ONLINE.TOKEN
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.STATUS
     *
     * @return the value of EOP_APP_ONLINE.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.STATUS
     *
     * @param status the value for EOP_APP_ONLINE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.TOKEN_STAMP
     *
     * @return the value of EOP_APP_ONLINE.TOKEN_STAMP
     *
     * @mbggenerated
     */
    public String getTokenStamp() {
        return tokenStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.TOKEN_STAMP
     *
     * @param tokenStamp the value for EOP_APP_ONLINE.TOKEN_STAMP
     *
     * @mbggenerated
     */
    public void setTokenStamp(String tokenStamp) {
        this.tokenStamp = tokenStamp == null ? null : tokenStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.CLIENT_IP
     *
     * @return the value of EOP_APP_ONLINE.CLIENT_IP
     *
     * @mbggenerated
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.CLIENT_IP
     *
     * @param clientIp the value for EOP_APP_ONLINE.CLIENT_IP
     *
     * @mbggenerated
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP_ONLINE.CREATE_DATE
     *
     * @return the value of EOP_APP_ONLINE.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP_ONLINE.CREATE_DATE
     *
     * @param createDate the value for EOP_APP_ONLINE.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}