package com.telecomjs.beans;

import java.io.Serializable;
import java.util.Date;

public class EopAppBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP.APP_ID
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP.APIKEY
     *
     * @mbggenerated
     */
    private String apikey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP.APP_SECRET
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP.APP_NAME
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_APP.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP.APP_ID
     *
     * @return the value of EOP_APP.APP_ID
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP.APP_ID
     *
     * @param appId the value for EOP_APP.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP.APIKEY
     *
     * @return the value of EOP_APP.APIKEY
     *
     * @mbggenerated
     */
    public String getApikey() {
        return apikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP.APIKEY
     *
     * @param apikey the value for EOP_APP.APIKEY
     *
     * @mbggenerated
     */
    public void setApikey(String apikey) {
        this.apikey = apikey == null ? null : apikey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP.APP_SECRET
     *
     * @return the value of EOP_APP.APP_SECRET
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP.APP_SECRET
     *
     * @param appSecret the value for EOP_APP.APP_SECRET
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP.APP_NAME
     *
     * @return the value of EOP_APP.APP_NAME
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP.APP_NAME
     *
     * @param appName the value for EOP_APP.APP_NAME
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_APP.CREATE_DATE
     *
     * @return the value of EOP_APP.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_APP.CREATE_DATE
     *
     * @param createDate the value for EOP_APP.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}