package com.telecomjs.beans;

import java.io.Serializable;
import java.util.Date;

public class EopResourceAccessLimitBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.limit_id
     *
     * @mbggenerated
     */
    private Integer limitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.app_id
     *
     * @mbggenerated
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.domain
     *
     * @mbggenerated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.limit_value
     *
     * @mbggenerated
     */
    private Integer limitValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eop_resource_access_limit.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.limit_id
     *
     * @return the value of eop_resource_access_limit.limit_id
     *
     * @mbggenerated
     */
    public Integer getLimitId() {
        return limitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.limit_id
     *
     * @param limitId the value for eop_resource_access_limit.limit_id
     *
     * @mbggenerated
     */
    public void setLimitId(Integer limitId) {
        this.limitId = limitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.app_id
     *
     * @return the value of eop_resource_access_limit.app_id
     *
     * @mbggenerated
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.app_id
     *
     * @param appId the value for eop_resource_access_limit.app_id
     *
     * @mbggenerated
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.domain
     *
     * @return the value of eop_resource_access_limit.domain
     *
     * @mbggenerated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.domain
     *
     * @param domain the value for eop_resource_access_limit.domain
     *
     * @mbggenerated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.method_name
     *
     * @return the value of eop_resource_access_limit.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.method_name
     *
     * @param methodName the value for eop_resource_access_limit.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.limit_value
     *
     * @return the value of eop_resource_access_limit.limit_value
     *
     * @mbggenerated
     */
    public Integer getLimitValue() {
        return limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.limit_value
     *
     * @param limitValue the value for eop_resource_access_limit.limit_value
     *
     * @mbggenerated
     */
    public void setLimitValue(Integer limitValue) {
        this.limitValue = limitValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eop_resource_access_limit.create_date
     *
     * @return the value of eop_resource_access_limit.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eop_resource_access_limit.create_date
     *
     * @param createDate the value for eop_resource_access_limit.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}