package com.telecomjs.beans;

import java.io.Serializable;
import java.util.Date;

public class EopResourceAccessLimitBean implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT_ID
     *
     * @mbggenerated
     */
    private Long limitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.APP_ID
     *
     * @mbggenerated
     */
    private Long appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.DOMAIN
     *
     * @mbggenerated
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.METHOD_NAME
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT
     *
     * @mbggenerated
     */
    private Long limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EOP_RESOURCE_ACCESS_LIMIT.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT_ID
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.LIMIT_ID
     *
     * @mbggenerated
     */
    public Long getLimitId() {
        return limitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT_ID
     *
     * @param limitId the value for EOP_RESOURCE_ACCESS_LIMIT.LIMIT_ID
     *
     * @mbggenerated
     */
    public void setLimitId(Long limitId) {
        this.limitId = limitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.APP_ID
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.APP_ID
     *
     * @mbggenerated
     */
    public Long getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.APP_ID
     *
     * @param appId the value for EOP_RESOURCE_ACCESS_LIMIT.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(Long appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.DOMAIN
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.DOMAIN
     *
     * @mbggenerated
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.DOMAIN
     *
     * @param domain the value for EOP_RESOURCE_ACCESS_LIMIT.DOMAIN
     *
     * @mbggenerated
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.METHOD_NAME
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.METHOD_NAME
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.METHOD_NAME
     *
     * @param methodName the value for EOP_RESOURCE_ACCESS_LIMIT.METHOD_NAME
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.LIMIT
     *
     * @mbggenerated
     */
    public Long getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.LIMIT
     *
     * @param limit the value for EOP_RESOURCE_ACCESS_LIMIT.LIMIT
     *
     * @mbggenerated
     */
    public void setLimit(Long limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EOP_RESOURCE_ACCESS_LIMIT.CREATE_DATE
     *
     * @return the value of EOP_RESOURCE_ACCESS_LIMIT.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EOP_RESOURCE_ACCESS_LIMIT.CREATE_DATE
     *
     * @param createDate the value for EOP_RESOURCE_ACCESS_LIMIT.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}