package com.telecomjs.beans;

import java.util.Date;

public class OfferBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_ID
     *
     * @mbggenerated
     */
    private String offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_NAME
     *
     * @mbggenerated
     */
    private String offerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.BRAND_ID
     *
     * @mbggenerated
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.CREATE_STAFF
     *
     * @mbggenerated
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.EFF_DATE
     *
     * @mbggenerated
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.EXP_DATE
     *
     * @mbggenerated
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.INITIAL_CRED_VALUE
     *
     * @mbggenerated
     */
    private String initialCredValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.IS_INDEPENDENT
     *
     * @mbggenerated
     */
    private String isIndependent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.MANAGE_GRADE
     *
     * @mbggenerated
     */
    private String manageGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.MANAGE_GRADE_PROV
     *
     * @mbggenerated
     */
    private String manageGradeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.MANAGE_REGION_ID
     *
     * @mbggenerated
     */
    private String manageRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_DESC
     *
     * @mbggenerated
     */
    private String offerDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_NBR
     *
     * @mbggenerated
     */
    private String offerNbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_PROVIDER_ID
     *
     * @mbggenerated
     */
    private String offerProviderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_SYS_NAME
     *
     * @mbggenerated
     */
    private String offerSysName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_SYS_NBR
     *
     * @mbggenerated
     */
    private String offerSysNbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_SYS_PY_NAME
     *
     * @mbggenerated
     */
    private String offerSysPyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_SYS_TYPE
     *
     * @mbggenerated
     */
    private String offerSysType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.OFFER_TYPE
     *
     * @mbggenerated
     */
    private String offerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.PRICE_PLAN_ID
     *
     * @mbggenerated
     */
    private String pricePlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.STATUS_CD
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    private String statusCdProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.STATUS_DATE
     *
     * @mbggenerated
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    private String updateStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.VALUE_ADDED_FLAG
     *
     * @mbggenerated
     */
    private String valueAddedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    private String extOfferId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    private String origOfferId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_ID
     *
     * @return the value of OFFER.OFFER_ID
     *
     * @mbggenerated
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_ID
     *
     * @param offerId the value for OFFER.OFFER_ID
     *
     * @mbggenerated
     */
    public void setOfferId(String offerId) {
        this.offerId = offerId == null ? null : offerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_NAME
     *
     * @return the value of OFFER.OFFER_NAME
     *
     * @mbggenerated
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_NAME
     *
     * @param offerName the value for OFFER.OFFER_NAME
     *
     * @mbggenerated
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName == null ? null : offerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.BRAND_ID
     *
     * @return the value of OFFER.BRAND_ID
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.BRAND_ID
     *
     * @param brandId the value for OFFER.BRAND_ID
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.CREATE_DATE
     *
     * @return the value of OFFER.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.CREATE_DATE
     *
     * @param createDate the value for OFFER.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.CREATE_STAFF
     *
     * @return the value of OFFER.CREATE_STAFF
     *
     * @mbggenerated
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.CREATE_STAFF
     *
     * @param createStaff the value for OFFER.CREATE_STAFF
     *
     * @mbggenerated
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.EFF_DATE
     *
     * @return the value of OFFER.EFF_DATE
     *
     * @mbggenerated
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.EFF_DATE
     *
     * @param effDate the value for OFFER.EFF_DATE
     *
     * @mbggenerated
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.EXP_DATE
     *
     * @return the value of OFFER.EXP_DATE
     *
     * @mbggenerated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.EXP_DATE
     *
     * @param expDate the value for OFFER.EXP_DATE
     *
     * @mbggenerated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.INITIAL_CRED_VALUE
     *
     * @return the value of OFFER.INITIAL_CRED_VALUE
     *
     * @mbggenerated
     */
    public String getInitialCredValue() {
        return initialCredValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.INITIAL_CRED_VALUE
     *
     * @param initialCredValue the value for OFFER.INITIAL_CRED_VALUE
     *
     * @mbggenerated
     */
    public void setInitialCredValue(String initialCredValue) {
        this.initialCredValue = initialCredValue == null ? null : initialCredValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.IS_INDEPENDENT
     *
     * @return the value of OFFER.IS_INDEPENDENT
     *
     * @mbggenerated
     */
    public String getIsIndependent() {
        return isIndependent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.IS_INDEPENDENT
     *
     * @param isIndependent the value for OFFER.IS_INDEPENDENT
     *
     * @mbggenerated
     */
    public void setIsIndependent(String isIndependent) {
        this.isIndependent = isIndependent == null ? null : isIndependent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.MANAGE_GRADE
     *
     * @return the value of OFFER.MANAGE_GRADE
     *
     * @mbggenerated
     */
    public String getManageGrade() {
        return manageGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.MANAGE_GRADE
     *
     * @param manageGrade the value for OFFER.MANAGE_GRADE
     *
     * @mbggenerated
     */
    public void setManageGrade(String manageGrade) {
        this.manageGrade = manageGrade == null ? null : manageGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.MANAGE_GRADE_PROV
     *
     * @return the value of OFFER.MANAGE_GRADE_PROV
     *
     * @mbggenerated
     */
    public String getManageGradeProv() {
        return manageGradeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.MANAGE_GRADE_PROV
     *
     * @param manageGradeProv the value for OFFER.MANAGE_GRADE_PROV
     *
     * @mbggenerated
     */
    public void setManageGradeProv(String manageGradeProv) {
        this.manageGradeProv = manageGradeProv == null ? null : manageGradeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.MANAGE_REGION_ID
     *
     * @return the value of OFFER.MANAGE_REGION_ID
     *
     * @mbggenerated
     */
    public String getManageRegionId() {
        return manageRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.MANAGE_REGION_ID
     *
     * @param manageRegionId the value for OFFER.MANAGE_REGION_ID
     *
     * @mbggenerated
     */
    public void setManageRegionId(String manageRegionId) {
        this.manageRegionId = manageRegionId == null ? null : manageRegionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_DESC
     *
     * @return the value of OFFER.OFFER_DESC
     *
     * @mbggenerated
     */
    public String getOfferDesc() {
        return offerDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_DESC
     *
     * @param offerDesc the value for OFFER.OFFER_DESC
     *
     * @mbggenerated
     */
    public void setOfferDesc(String offerDesc) {
        this.offerDesc = offerDesc == null ? null : offerDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_NBR
     *
     * @return the value of OFFER.OFFER_NBR
     *
     * @mbggenerated
     */
    public String getOfferNbr() {
        return offerNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_NBR
     *
     * @param offerNbr the value for OFFER.OFFER_NBR
     *
     * @mbggenerated
     */
    public void setOfferNbr(String offerNbr) {
        this.offerNbr = offerNbr == null ? null : offerNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_PROVIDER_ID
     *
     * @return the value of OFFER.OFFER_PROVIDER_ID
     *
     * @mbggenerated
     */
    public String getOfferProviderId() {
        return offerProviderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_PROVIDER_ID
     *
     * @param offerProviderId the value for OFFER.OFFER_PROVIDER_ID
     *
     * @mbggenerated
     */
    public void setOfferProviderId(String offerProviderId) {
        this.offerProviderId = offerProviderId == null ? null : offerProviderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_SYS_NAME
     *
     * @return the value of OFFER.OFFER_SYS_NAME
     *
     * @mbggenerated
     */
    public String getOfferSysName() {
        return offerSysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_SYS_NAME
     *
     * @param offerSysName the value for OFFER.OFFER_SYS_NAME
     *
     * @mbggenerated
     */
    public void setOfferSysName(String offerSysName) {
        this.offerSysName = offerSysName == null ? null : offerSysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_SYS_NBR
     *
     * @return the value of OFFER.OFFER_SYS_NBR
     *
     * @mbggenerated
     */
    public String getOfferSysNbr() {
        return offerSysNbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_SYS_NBR
     *
     * @param offerSysNbr the value for OFFER.OFFER_SYS_NBR
     *
     * @mbggenerated
     */
    public void setOfferSysNbr(String offerSysNbr) {
        this.offerSysNbr = offerSysNbr == null ? null : offerSysNbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_SYS_PY_NAME
     *
     * @return the value of OFFER.OFFER_SYS_PY_NAME
     *
     * @mbggenerated
     */
    public String getOfferSysPyName() {
        return offerSysPyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_SYS_PY_NAME
     *
     * @param offerSysPyName the value for OFFER.OFFER_SYS_PY_NAME
     *
     * @mbggenerated
     */
    public void setOfferSysPyName(String offerSysPyName) {
        this.offerSysPyName = offerSysPyName == null ? null : offerSysPyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_SYS_TYPE
     *
     * @return the value of OFFER.OFFER_SYS_TYPE
     *
     * @mbggenerated
     */
    public String getOfferSysType() {
        return offerSysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_SYS_TYPE
     *
     * @param offerSysType the value for OFFER.OFFER_SYS_TYPE
     *
     * @mbggenerated
     */
    public void setOfferSysType(String offerSysType) {
        this.offerSysType = offerSysType == null ? null : offerSysType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.OFFER_TYPE
     *
     * @return the value of OFFER.OFFER_TYPE
     *
     * @mbggenerated
     */
    public String getOfferType() {
        return offerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.OFFER_TYPE
     *
     * @param offerType the value for OFFER.OFFER_TYPE
     *
     * @mbggenerated
     */
    public void setOfferType(String offerType) {
        this.offerType = offerType == null ? null : offerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.PRICE_PLAN_ID
     *
     * @return the value of OFFER.PRICE_PLAN_ID
     *
     * @mbggenerated
     */
    public String getPricePlanId() {
        return pricePlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.PRICE_PLAN_ID
     *
     * @param pricePlanId the value for OFFER.PRICE_PLAN_ID
     *
     * @mbggenerated
     */
    public void setPricePlanId(String pricePlanId) {
        this.pricePlanId = pricePlanId == null ? null : pricePlanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.REMARK
     *
     * @return the value of OFFER.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.REMARK
     *
     * @param remark the value for OFFER.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.STATUS_CD
     *
     * @return the value of OFFER.STATUS_CD
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.STATUS_CD
     *
     * @param statusCd the value for OFFER.STATUS_CD
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.STATUS_CD_PROV
     *
     * @return the value of OFFER.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    public String getStatusCdProv() {
        return statusCdProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.STATUS_CD_PROV
     *
     * @param statusCdProv the value for OFFER.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    public void setStatusCdProv(String statusCdProv) {
        this.statusCdProv = statusCdProv == null ? null : statusCdProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.STATUS_DATE
     *
     * @return the value of OFFER.STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.STATUS_DATE
     *
     * @param statusDate the value for OFFER.STATUS_DATE
     *
     * @mbggenerated
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.UPDATE_DATE
     *
     * @return the value of OFFER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.UPDATE_DATE
     *
     * @param updateDate the value for OFFER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.UPDATE_STAFF
     *
     * @return the value of OFFER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.UPDATE_STAFF
     *
     * @param updateStaff the value for OFFER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.VALUE_ADDED_FLAG
     *
     * @return the value of OFFER.VALUE_ADDED_FLAG
     *
     * @mbggenerated
     */
    public String getValueAddedFlag() {
        return valueAddedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.VALUE_ADDED_FLAG
     *
     * @param valueAddedFlag the value for OFFER.VALUE_ADDED_FLAG
     *
     * @mbggenerated
     */
    public void setValueAddedFlag(String valueAddedFlag) {
        this.valueAddedFlag = valueAddedFlag == null ? null : valueAddedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.EXT_OFFER_ID
     *
     * @return the value of OFFER.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    public String getExtOfferId() {
        return extOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.EXT_OFFER_ID
     *
     * @param extOfferId the value for OFFER.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    public void setExtOfferId(String extOfferId) {
        this.extOfferId = extOfferId == null ? null : extOfferId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER.ORIG_OFFER_ID
     *
     * @return the value of OFFER.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    public String getOrigOfferId() {
        return origOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER.ORIG_OFFER_ID
     *
     * @param origOfferId the value for OFFER.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    public void setOrigOfferId(String origOfferId) {
        this.origOfferId = origOfferId == null ? null : origOfferId.trim();
    }
}