package com.telecomjs.beans;

import java.util.Date;

public class OfferInstBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OFFER_INST_ID
     *
     * @mbggenerated
     */
    private String offerInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    private Date busiModDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.CHANNEL_ID
     *
     * @mbggenerated
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    private String createOrdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.EFF_DATE
     *
     * @mbggenerated
     */
    private Date effDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.EXP_DATE
     *
     * @mbggenerated
     */
    private Date expDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.EXP_PROC_METHOD
     *
     * @mbggenerated
     */
    private String expProcMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.LAN_ID
     *
     * @mbggenerated
     */
    private String lanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    private String lastOrderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OFFER_AGREE_ID
     *
     * @mbggenerated
     */
    private String offerAgreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OFFER_ID
     *
     * @mbggenerated
     */
    private String offerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    private String extOfferId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OFFER_TYPE
     *
     * @mbggenerated
     */
    private String offerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OFFER_TYPE_PROV
     *
     * @mbggenerated
     */
    private String offerTypeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    private String ownerCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.REGION_ID
     *
     * @mbggenerated
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.STATUS_CD
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    private String updateStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    private String origOfferId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OFFER_INST.EXT_OFFER_INST_ID
     *
     * @mbggenerated
     */
    private String extOfferInstId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OFFER_INST_ID
     *
     * @return the value of OFFER_INST.OFFER_INST_ID
     *
     * @mbggenerated
     */
    public String getOfferInstId() {
        return offerInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OFFER_INST_ID
     *
     * @param offerInstId the value for OFFER_INST.OFFER_INST_ID
     *
     * @mbggenerated
     */
    public void setOfferInstId(String offerInstId) {
        this.offerInstId = offerInstId == null ? null : offerInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.BUSI_MOD_DATE
     *
     * @return the value of OFFER_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    public Date getBusiModDate() {
        return busiModDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.BUSI_MOD_DATE
     *
     * @param busiModDate the value for OFFER_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    public void setBusiModDate(Date busiModDate) {
        this.busiModDate = busiModDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.CHANNEL_ID
     *
     * @return the value of OFFER_INST.CHANNEL_ID
     *
     * @mbggenerated
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.CHANNEL_ID
     *
     * @param channelId the value for OFFER_INST.CHANNEL_ID
     *
     * @mbggenerated
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.CREATE_DATE
     *
     * @return the value of OFFER_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.CREATE_DATE
     *
     * @param createDate the value for OFFER_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.CREATE_ORD_ID
     *
     * @return the value of OFFER_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    public String getCreateOrdId() {
        return createOrdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.CREATE_ORD_ID
     *
     * @param createOrdId the value for OFFER_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    public void setCreateOrdId(String createOrdId) {
        this.createOrdId = createOrdId == null ? null : createOrdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.CREATE_STAFF
     *
     * @return the value of OFFER_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.CREATE_STAFF
     *
     * @param createStaff the value for OFFER_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.EFF_DATE
     *
     * @return the value of OFFER_INST.EFF_DATE
     *
     * @mbggenerated
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.EFF_DATE
     *
     * @param effDate the value for OFFER_INST.EFF_DATE
     *
     * @mbggenerated
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.EXP_DATE
     *
     * @return the value of OFFER_INST.EXP_DATE
     *
     * @mbggenerated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.EXP_DATE
     *
     * @param expDate the value for OFFER_INST.EXP_DATE
     *
     * @mbggenerated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.EXP_PROC_METHOD
     *
     * @return the value of OFFER_INST.EXP_PROC_METHOD
     *
     * @mbggenerated
     */
    public String getExpProcMethod() {
        return expProcMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.EXP_PROC_METHOD
     *
     * @param expProcMethod the value for OFFER_INST.EXP_PROC_METHOD
     *
     * @mbggenerated
     */
    public void setExpProcMethod(String expProcMethod) {
        this.expProcMethod = expProcMethod == null ? null : expProcMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.LAN_ID
     *
     * @return the value of OFFER_INST.LAN_ID
     *
     * @mbggenerated
     */
    public String getLanId() {
        return lanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.LAN_ID
     *
     * @param lanId the value for OFFER_INST.LAN_ID
     *
     * @mbggenerated
     */
    public void setLanId(String lanId) {
        this.lanId = lanId == null ? null : lanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.LAST_ORDER_ITEM_ID
     *
     * @return the value of OFFER_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public String getLastOrderItemId() {
        return lastOrderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.LAST_ORDER_ITEM_ID
     *
     * @param lastOrderItemId the value for OFFER_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public void setLastOrderItemId(String lastOrderItemId) {
        this.lastOrderItemId = lastOrderItemId == null ? null : lastOrderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OFFER_AGREE_ID
     *
     * @return the value of OFFER_INST.OFFER_AGREE_ID
     *
     * @mbggenerated
     */
    public String getOfferAgreeId() {
        return offerAgreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OFFER_AGREE_ID
     *
     * @param offerAgreeId the value for OFFER_INST.OFFER_AGREE_ID
     *
     * @mbggenerated
     */
    public void setOfferAgreeId(String offerAgreeId) {
        this.offerAgreeId = offerAgreeId == null ? null : offerAgreeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OFFER_ID
     *
     * @return the value of OFFER_INST.OFFER_ID
     *
     * @mbggenerated
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OFFER_ID
     *
     * @param offerId the value for OFFER_INST.OFFER_ID
     *
     * @mbggenerated
     */
    public void setOfferId(String offerId) {
        this.offerId = offerId == null ? null : offerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.EXT_OFFER_ID
     *
     * @return the value of OFFER_INST.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    public String getExtOfferId() {
        return extOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.EXT_OFFER_ID
     *
     * @param extOfferId the value for OFFER_INST.EXT_OFFER_ID
     *
     * @mbggenerated
     */
    public void setExtOfferId(String extOfferId) {
        this.extOfferId = extOfferId == null ? null : extOfferId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OFFER_TYPE
     *
     * @return the value of OFFER_INST.OFFER_TYPE
     *
     * @mbggenerated
     */
    public String getOfferType() {
        return offerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OFFER_TYPE
     *
     * @param offerType the value for OFFER_INST.OFFER_TYPE
     *
     * @mbggenerated
     */
    public void setOfferType(String offerType) {
        this.offerType = offerType == null ? null : offerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OFFER_TYPE_PROV
     *
     * @return the value of OFFER_INST.OFFER_TYPE_PROV
     *
     * @mbggenerated
     */
    public String getOfferTypeProv() {
        return offerTypeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OFFER_TYPE_PROV
     *
     * @param offerTypeProv the value for OFFER_INST.OFFER_TYPE_PROV
     *
     * @mbggenerated
     */
    public void setOfferTypeProv(String offerTypeProv) {
        this.offerTypeProv = offerTypeProv == null ? null : offerTypeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.OWNER_CUST_ID
     *
     * @return the value of OFFER_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    public String getOwnerCustId() {
        return ownerCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.OWNER_CUST_ID
     *
     * @param ownerCustId the value for OFFER_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    public void setOwnerCustId(String ownerCustId) {
        this.ownerCustId = ownerCustId == null ? null : ownerCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.REGION_ID
     *
     * @return the value of OFFER_INST.REGION_ID
     *
     * @mbggenerated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.REGION_ID
     *
     * @param regionId the value for OFFER_INST.REGION_ID
     *
     * @mbggenerated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.REMARK
     *
     * @return the value of OFFER_INST.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.REMARK
     *
     * @param remark the value for OFFER_INST.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.STATUS_CD
     *
     * @return the value of OFFER_INST.STATUS_CD
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.STATUS_CD
     *
     * @param statusCd the value for OFFER_INST.STATUS_CD
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.STATUS_DATE
     *
     * @return the value of OFFER_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.STATUS_DATE
     *
     * @param statusDate the value for OFFER_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.UPDATE_DATE
     *
     * @return the value of OFFER_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.UPDATE_DATE
     *
     * @param updateDate the value for OFFER_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.UPDATE_STAFF
     *
     * @return the value of OFFER_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.UPDATE_STAFF
     *
     * @param updateStaff the value for OFFER_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.ORIG_OFFER_ID
     *
     * @return the value of OFFER_INST.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    public String getOrigOfferId() {
        return origOfferId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.ORIG_OFFER_ID
     *
     * @param origOfferId the value for OFFER_INST.ORIG_OFFER_ID
     *
     * @mbggenerated
     */
    public void setOrigOfferId(String origOfferId) {
        this.origOfferId = origOfferId == null ? null : origOfferId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OFFER_INST.EXT_OFFER_INST_ID
     *
     * @return the value of OFFER_INST.EXT_OFFER_INST_ID
     *
     * @mbggenerated
     */
    public String getExtOfferInstId() {
        return extOfferInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OFFER_INST.EXT_OFFER_INST_ID
     *
     * @param extOfferInstId the value for OFFER_INST.EXT_OFFER_INST_ID
     *
     * @mbggenerated
     */
    public void setExtOfferInstId(String extOfferInstId) {
        this.extOfferInstId = extOfferInstId == null ? null : extOfferInstId.trim();
    }
}