package com.telecomjs.mapper;

import com.telecomjs.entities.EopAppPermission;

public interface EopAppPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_APP_PERMISSION
     *
     * @mbggenerated
     */
    int insert(EopAppPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_APP_PERMISSION
     *
     * @mbggenerated
     */
    int insertSelective(EopAppPermission record);
}