package com.telecomjs.mapper;

import com.telecomjs.entities.EopAppAccess;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;

public interface EopAppAccessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_APP_ACCESS
     *
     * @mbggenerated
     */

    int insert(EopAppAccess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_APP_ACCESS
     *
     * @mbggenerated
     */
    int insertSelective(EopAppAccess record);
    @Cacheable(value = "auth" , key = "'EopAppAccess#'+ #root.methodName+'#'+T(java.lang.String).valueOf(#p0)+','+#p1")
    public EopAppAccess selectByAppIdAndDate(@Param("appId") long appId, @Param("statDate") String statDate);

    @CacheEvict(value = "auth" ,key = "'EopAppAccess#'+ #root.methodName+'#'+T(java.lang.String).valueOf(#p0)+','+#p1")
    public int updateByAppIdAndDate(@Param("appId") long appId, @Param("statDate") String statDate);
}