package com.telecomjs.mapper;

import com.telecomjs.entities.EopResourceAccessLimit;
import org.springframework.cache.annotation.Cacheable;

import java.util.List;

public interface EopResourceAccessLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_RESOURCE_ACCESS_LIMIT
     *
     * @mbggenerated
     */
    //int countByExample(EopResourceAccessLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_RESOURCE_ACCESS_LIMIT
     *
     * @mbggenerated
     */
    int insert(EopResourceAccessLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_RESOURCE_ACCESS_LIMIT
     *
     * @mbggenerated
     */
    int insertSelective(EopResourceAccessLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_RESOURCE_ACCESS_LIMIT
     *
     * @mbggenerated
     */
    @SuppressWarnings("UnnecessaryInterfaceModifier")
    @Cacheable(value = "auth" ,key = "'accesslimit#'+#root.methodName+'#'+T(java.lang.String).valueOf(#p0)")
    public List<EopResourceAccessLimit> selectByAppId(long appId);
}