package com.telecomjs.mapper;

import com.telecomjs.entities.EopUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.Cacheable;

@SuppressWarnings("UnnecessaryInterfaceModifier")
public interface EopUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_USER
     *
     * @mbggenerated
     */
    int insert(EopUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EOP_USER
     *
     * @mbggenerated
     */
    int insertSelective(EopUser record);

    /**
     * 根据传入的用户名和密码验证
     * @param username
     * @param password
     * @return
     */
    @Cacheable(value = "auth",key = "'getUserByNameAndPassword#'+#username")
    public EopUser getUserByNameAndPassword(@Param("username") String username,@Param("password") String password);
}