package com.telecomjs.entities;

import java.io.Serializable;
import java.util.Date;

public class ProdInst implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PROD_INST_ID
     *
     * @mbggenerated
     */
    private String prodInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ACCOUNT
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ACC_NUM
     *
     * @mbggenerated
     */
    private String accNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ACC_PROD_INST_ID
     *
     * @mbggenerated
     */
    private String accProdInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ACT_DATE
     *
     * @mbggenerated
     */
    private Date actDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ADDRESS_DESC
     *
     * @mbggenerated
     */
    private String addressDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.ADDRESS_ID
     *
     * @mbggenerated
     */
    private String addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.BEGIN_RENT_DATE
     *
     * @mbggenerated
     */
    private Date beginRentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    private Date busiModDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    private String createOrdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.EXCH_ID
     *
     * @mbggenerated
     */
    private String exchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.EXT_PROD_INST_ID
     *
     * @mbggenerated
     */
    private String extProdInstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.FIRST_FINISH_DATE
     *
     * @mbggenerated
     */
    private Date firstFinishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.LAN_ID
     *
     * @mbggenerated
     */
    private String lanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    private String lastOrderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    private String ownerCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PAYMENT_MODE_CD
     *
     * @mbggenerated
     */
    private String paymentModeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PAYMENT_MODE_CD_PROV
     *
     * @mbggenerated
     */
    private String paymentModeCdProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PROD_ID
     *
     * @mbggenerated
     */
    private String prodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.EXT_PROD_ID
     *
     * @mbggenerated
     */
    private String extProdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PROD_INST_PWD
     *
     * @mbggenerated
     */
    private String prodInstPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.PROD_USE_TYPE
     *
     * @mbggenerated
     */
    private String prodUseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.REGION_ID
     *
     * @mbggenerated
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.STATUS_CD
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    private String statusCdProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.STOP_RENT_DATE
     *
     * @mbggenerated
     */
    private Date stopRentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    private String updateStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROD_INST.USE_CUST_ID
     *
     * @mbggenerated
     */
    private String useCustId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PROD_INST_ID
     *
     * @return the value of PROD_INST.PROD_INST_ID
     *
     * @mbggenerated
     */
    public String getProdInstId() {
        return prodInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PROD_INST_ID
     *
     * @param prodInstId the value for PROD_INST.PROD_INST_ID
     *
     * @mbggenerated
     */
    public void setProdInstId(String prodInstId) {
        this.prodInstId = prodInstId == null ? null : prodInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ACCOUNT
     *
     * @return the value of PROD_INST.ACCOUNT
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ACCOUNT
     *
     * @param account the value for PROD_INST.ACCOUNT
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ACC_NUM
     *
     * @return the value of PROD_INST.ACC_NUM
     *
     * @mbggenerated
     */
    public String getAccNum() {
        return accNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ACC_NUM
     *
     * @param accNum the value for PROD_INST.ACC_NUM
     *
     * @mbggenerated
     */
    public void setAccNum(String accNum) {
        this.accNum = accNum == null ? null : accNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ACC_PROD_INST_ID
     *
     * @return the value of PROD_INST.ACC_PROD_INST_ID
     *
     * @mbggenerated
     */
    public String getAccProdInstId() {
        return accProdInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ACC_PROD_INST_ID
     *
     * @param accProdInstId the value for PROD_INST.ACC_PROD_INST_ID
     *
     * @mbggenerated
     */
    public void setAccProdInstId(String accProdInstId) {
        this.accProdInstId = accProdInstId == null ? null : accProdInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ACT_DATE
     *
     * @return the value of PROD_INST.ACT_DATE
     *
     * @mbggenerated
     */
    public Date getActDate() {
        return actDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ACT_DATE
     *
     * @param actDate the value for PROD_INST.ACT_DATE
     *
     * @mbggenerated
     */
    public void setActDate(Date actDate) {
        this.actDate = actDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ADDRESS_DESC
     *
     * @return the value of PROD_INST.ADDRESS_DESC
     *
     * @mbggenerated
     */
    public String getAddressDesc() {
        return addressDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ADDRESS_DESC
     *
     * @param addressDesc the value for PROD_INST.ADDRESS_DESC
     *
     * @mbggenerated
     */
    public void setAddressDesc(String addressDesc) {
        this.addressDesc = addressDesc == null ? null : addressDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.ADDRESS_ID
     *
     * @return the value of PROD_INST.ADDRESS_ID
     *
     * @mbggenerated
     */
    public String getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.ADDRESS_ID
     *
     * @param addressId the value for PROD_INST.ADDRESS_ID
     *
     * @mbggenerated
     */
    public void setAddressId(String addressId) {
        this.addressId = addressId == null ? null : addressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.BEGIN_RENT_DATE
     *
     * @return the value of PROD_INST.BEGIN_RENT_DATE
     *
     * @mbggenerated
     */
    public Date getBeginRentDate() {
        return beginRentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.BEGIN_RENT_DATE
     *
     * @param beginRentDate the value for PROD_INST.BEGIN_RENT_DATE
     *
     * @mbggenerated
     */
    public void setBeginRentDate(Date beginRentDate) {
        this.beginRentDate = beginRentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.BUSI_MOD_DATE
     *
     * @return the value of PROD_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    public Date getBusiModDate() {
        return busiModDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.BUSI_MOD_DATE
     *
     * @param busiModDate the value for PROD_INST.BUSI_MOD_DATE
     *
     * @mbggenerated
     */
    public void setBusiModDate(Date busiModDate) {
        this.busiModDate = busiModDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.CREATE_DATE
     *
     * @return the value of PROD_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.CREATE_DATE
     *
     * @param createDate the value for PROD_INST.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.CREATE_ORD_ID
     *
     * @return the value of PROD_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    public String getCreateOrdId() {
        return createOrdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.CREATE_ORD_ID
     *
     * @param createOrdId the value for PROD_INST.CREATE_ORD_ID
     *
     * @mbggenerated
     */
    public void setCreateOrdId(String createOrdId) {
        this.createOrdId = createOrdId == null ? null : createOrdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.CREATE_STAFF
     *
     * @return the value of PROD_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.CREATE_STAFF
     *
     * @param createStaff the value for PROD_INST.CREATE_STAFF
     *
     * @mbggenerated
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.EXCH_ID
     *
     * @return the value of PROD_INST.EXCH_ID
     *
     * @mbggenerated
     */
    public String getExchId() {
        return exchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.EXCH_ID
     *
     * @param exchId the value for PROD_INST.EXCH_ID
     *
     * @mbggenerated
     */
    public void setExchId(String exchId) {
        this.exchId = exchId == null ? null : exchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.EXT_PROD_INST_ID
     *
     * @return the value of PROD_INST.EXT_PROD_INST_ID
     *
     * @mbggenerated
     */
    public String getExtProdInstId() {
        return extProdInstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.EXT_PROD_INST_ID
     *
     * @param extProdInstId the value for PROD_INST.EXT_PROD_INST_ID
     *
     * @mbggenerated
     */
    public void setExtProdInstId(String extProdInstId) {
        this.extProdInstId = extProdInstId == null ? null : extProdInstId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.FIRST_FINISH_DATE
     *
     * @return the value of PROD_INST.FIRST_FINISH_DATE
     *
     * @mbggenerated
     */
    public Date getFirstFinishDate() {
        return firstFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.FIRST_FINISH_DATE
     *
     * @param firstFinishDate the value for PROD_INST.FIRST_FINISH_DATE
     *
     * @mbggenerated
     */
    public void setFirstFinishDate(Date firstFinishDate) {
        this.firstFinishDate = firstFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.LAN_ID
     *
     * @return the value of PROD_INST.LAN_ID
     *
     * @mbggenerated
     */
    public String getLanId() {
        return lanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.LAN_ID
     *
     * @param lanId the value for PROD_INST.LAN_ID
     *
     * @mbggenerated
     */
    public void setLanId(String lanId) {
        this.lanId = lanId == null ? null : lanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.LAST_ORDER_ITEM_ID
     *
     * @return the value of PROD_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public String getLastOrderItemId() {
        return lastOrderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.LAST_ORDER_ITEM_ID
     *
     * @param lastOrderItemId the value for PROD_INST.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public void setLastOrderItemId(String lastOrderItemId) {
        this.lastOrderItemId = lastOrderItemId == null ? null : lastOrderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.OWNER_CUST_ID
     *
     * @return the value of PROD_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    public String getOwnerCustId() {
        return ownerCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.OWNER_CUST_ID
     *
     * @param ownerCustId the value for PROD_INST.OWNER_CUST_ID
     *
     * @mbggenerated
     */
    public void setOwnerCustId(String ownerCustId) {
        this.ownerCustId = ownerCustId == null ? null : ownerCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PAYMENT_MODE_CD
     *
     * @return the value of PROD_INST.PAYMENT_MODE_CD
     *
     * @mbggenerated
     */
    public String getPaymentModeCd() {
        return paymentModeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PAYMENT_MODE_CD
     *
     * @param paymentModeCd the value for PROD_INST.PAYMENT_MODE_CD
     *
     * @mbggenerated
     */
    public void setPaymentModeCd(String paymentModeCd) {
        this.paymentModeCd = paymentModeCd == null ? null : paymentModeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PAYMENT_MODE_CD_PROV
     *
     * @return the value of PROD_INST.PAYMENT_MODE_CD_PROV
     *
     * @mbggenerated
     */
    public String getPaymentModeCdProv() {
        return paymentModeCdProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PAYMENT_MODE_CD_PROV
     *
     * @param paymentModeCdProv the value for PROD_INST.PAYMENT_MODE_CD_PROV
     *
     * @mbggenerated
     */
    public void setPaymentModeCdProv(String paymentModeCdProv) {
        this.paymentModeCdProv = paymentModeCdProv == null ? null : paymentModeCdProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PROD_ID
     *
     * @return the value of PROD_INST.PROD_ID
     *
     * @mbggenerated
     */
    public String getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PROD_ID
     *
     * @param prodId the value for PROD_INST.PROD_ID
     *
     * @mbggenerated
     */
    public void setProdId(String prodId) {
        this.prodId = prodId == null ? null : prodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.EXT_PROD_ID
     *
     * @return the value of PROD_INST.EXT_PROD_ID
     *
     * @mbggenerated
     */
    public String getExtProdId() {
        return extProdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.EXT_PROD_ID
     *
     * @param extProdId the value for PROD_INST.EXT_PROD_ID
     *
     * @mbggenerated
     */
    public void setExtProdId(String extProdId) {
        this.extProdId = extProdId == null ? null : extProdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PROD_INST_PWD
     *
     * @return the value of PROD_INST.PROD_INST_PWD
     *
     * @mbggenerated
     */
    public String getProdInstPwd() {
        return prodInstPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PROD_INST_PWD
     *
     * @param prodInstPwd the value for PROD_INST.PROD_INST_PWD
     *
     * @mbggenerated
     */
    public void setProdInstPwd(String prodInstPwd) {
        this.prodInstPwd = prodInstPwd == null ? null : prodInstPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.PROD_USE_TYPE
     *
     * @return the value of PROD_INST.PROD_USE_TYPE
     *
     * @mbggenerated
     */
    public String getProdUseType() {
        return prodUseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.PROD_USE_TYPE
     *
     * @param prodUseType the value for PROD_INST.PROD_USE_TYPE
     *
     * @mbggenerated
     */
    public void setProdUseType(String prodUseType) {
        this.prodUseType = prodUseType == null ? null : prodUseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.REGION_ID
     *
     * @return the value of PROD_INST.REGION_ID
     *
     * @mbggenerated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.REGION_ID
     *
     * @param regionId the value for PROD_INST.REGION_ID
     *
     * @mbggenerated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.REMARK
     *
     * @return the value of PROD_INST.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.REMARK
     *
     * @param remark the value for PROD_INST.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.STATUS_CD
     *
     * @return the value of PROD_INST.STATUS_CD
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.STATUS_CD
     *
     * @param statusCd the value for PROD_INST.STATUS_CD
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.STATUS_CD_PROV
     *
     * @return the value of PROD_INST.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    public String getStatusCdProv() {
        return statusCdProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.STATUS_CD_PROV
     *
     * @param statusCdProv the value for PROD_INST.STATUS_CD_PROV
     *
     * @mbggenerated
     */
    public void setStatusCdProv(String statusCdProv) {
        this.statusCdProv = statusCdProv == null ? null : statusCdProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.STATUS_DATE
     *
     * @return the value of PROD_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.STATUS_DATE
     *
     * @param statusDate the value for PROD_INST.STATUS_DATE
     *
     * @mbggenerated
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.STOP_RENT_DATE
     *
     * @return the value of PROD_INST.STOP_RENT_DATE
     *
     * @mbggenerated
     */
    public Date getStopRentDate() {
        return stopRentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.STOP_RENT_DATE
     *
     * @param stopRentDate the value for PROD_INST.STOP_RENT_DATE
     *
     * @mbggenerated
     */
    public void setStopRentDate(Date stopRentDate) {
        this.stopRentDate = stopRentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.UPDATE_DATE
     *
     * @return the value of PROD_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.UPDATE_DATE
     *
     * @param updateDate the value for PROD_INST.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.UPDATE_STAFF
     *
     * @return the value of PROD_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.UPDATE_STAFF
     *
     * @param updateStaff the value for PROD_INST.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROD_INST.USE_CUST_ID
     *
     * @return the value of PROD_INST.USE_CUST_ID
     *
     * @mbggenerated
     */
    public String getUseCustId() {
        return useCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROD_INST.USE_CUST_ID
     *
     * @param useCustId the value for PROD_INST.USE_CUST_ID
     *
     * @mbggenerated
     */
    public void setUseCustId(String useCustId) {
        this.useCustId = useCustId == null ? null : useCustId.trim();
    }
}