package com.telecomjs.mapper;

import com.telecomjs.entities.Offer;

public interface OfferMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER
     *
     * @mbggenerated
     */
    int insert(Offer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER
     *
     * @mbggenerated
     */
    int insertSelective(Offer record);
}