package com.telecomjs.mapper;

import com.telecomjs.entities.OfferInst;

import java.util.List;

public interface OfferInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String offerInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    int insert(OfferInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    int insertSelective(OfferInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    OfferInst selectByPrimaryKey(String offerInstId);

    List<OfferInst> queryByProdId(String prodId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OfferInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OFFER_INST
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OfferInst record);
}