package com.telecomjs.mapper;

import com.telecomjs.entities.ProdInst;

import java.util.List;

public interface ProdInstMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String prodInstId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    int insert(ProdInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    int insertSelective(ProdInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    ProdInst selectByPrimaryKey(String prodInstId);

    /**
     * 根据号码查询产品信息
     * @param accNbr 接入号码
     * @return 产品信息bean
     */
    ProdInst selectByAccNbr(String accNbr);

    List<ProdInst> queryByPartyId(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProdInst record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROD_INST
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProdInst record);
}