package com.telecomjs.mapper;

import com.telecomjs.entities.EopResourceAccessLimit;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.Cacheable;

import java.util.List;

public interface EopResourceAccessLimitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eop_resource_access_limit
     *
     * @mbggenerated
     */
    int insert(EopResourceAccessLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eop_resource_access_limit
     *
     * @mbggenerated
     */
    int insertSelective(EopResourceAccessLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eop_resource_access_limit
     *
     * @mbggenerated
     */
    //int updateByExampleSelective(@Param("record") EopResourceAccessLimit record, @Param("example") EopResourceAccessLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eop_resource_access_limit
     *
     * @mbggenerated
     */
    //int updateByExample(@Param("record") EopResourceAccessLimit record, @Param("example") EopResourceAccessLimitExample example);

    @Cacheable(value = "auth" ,key = "'EopResourceAccessLimit#'+#root.methodName+'#'+T(java.lang.String).valueOf(#p0)")
    public List<EopResourceAccessLimit> selectByAppId(@Param("appId") long appId);


}