package com.telecomjs.mapper;

import com.telecomjs.entities.Party;
import org.springframework.cache.annotation.Cacheable;

public interface PartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    int insert(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    int insertSelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    @Cacheable(value = "custom")
    public Party selectByPrimaryKey(String partyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Party record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PARTY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Party record);
}