package com.telecomjs.entities;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_ID
     *
     * @mbggenerated
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.COMMON_REGION_ID
     *
     * @mbggenerated
     */
    private String commonRegionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CREATE_DATE
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CREATE_STAFF
     *
     * @mbggenerated
     */
    private String createStaff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_ADDR
     *
     * @mbggenerated
     */
    private String custAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_AREA_GRADE
     *
     * @mbggenerated
     */
    private String custAreaGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_AREA_GRADE_PROV
     *
     * @mbggenerated
     */
    private String custAreaGradeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_CONTROL_LEVEL
     *
     * @mbggenerated
     */
    private String custControlLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_NAME
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_NUMBER
     *
     * @mbggenerated
     */
    private String custNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_ORDER_ID
     *
     * @mbggenerated
     */
    private String custOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_SOURCE_ID
     *
     * @mbggenerated
     */
    private String custSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_STATUS_CD
     *
     * @mbggenerated
     */
    private String custStatusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_STATUS_DATE
     *
     * @mbggenerated
     */
    private Date custStatusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_SUB_TYPE
     *
     * @mbggenerated
     */
    private String custSubType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_SUB_TYPE_PROV
     *
     * @mbggenerated
     */
    private String custSubTypeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_TYPE
     *
     * @mbggenerated
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.CUST_TYPE_PROV
     *
     * @mbggenerated
     */
    private String custTypeProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.DISTRIBUTOR_ID
     *
     * @mbggenerated
     */
    private String distributorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.ENTER_DATE
     *
     * @mbggenerated
     */
    private Date enterDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.EXT_CUST_ID
     *
     * @mbggenerated
     */
    private String extCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.INDUSTRY_TYPE_ID
     *
     * @mbggenerated
     */
    private String industryTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.IS_INSTEAD
     *
     * @mbggenerated
     */
    private String isInstead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.IS_REALNAME
     *
     * @mbggenerated
     */
    private String isRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    private String lastOrderItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.PARTY_ID
     *
     * @mbggenerated
     */
    private String partyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.SECRECY_LEV
     *
     * @mbggenerated
     */
    private String secrecyLev;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.SECRECY_LEV_PROV
     *
     * @mbggenerated
     */
    private String secrecyLevProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.STATUS_CD
     *
     * @mbggenerated
     */
    private String statusCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.STATUS_DATE
     *
     * @mbggenerated
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.UPDATE_DATE
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CUSTOMER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    private String updateStaff;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_ID
     *
     * @return the value of CUSTOMER.CUST_ID
     *
     * @mbggenerated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_ID
     *
     * @param custId the value for CUSTOMER.CUST_ID
     *
     * @mbggenerated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.COMMON_REGION_ID
     *
     * @return the value of CUSTOMER.COMMON_REGION_ID
     *
     * @mbggenerated
     */
    public String getCommonRegionId() {
        return commonRegionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.COMMON_REGION_ID
     *
     * @param commonRegionId the value for CUSTOMER.COMMON_REGION_ID
     *
     * @mbggenerated
     */
    public void setCommonRegionId(String commonRegionId) {
        this.commonRegionId = commonRegionId == null ? null : commonRegionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CREATE_DATE
     *
     * @return the value of CUSTOMER.CREATE_DATE
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CREATE_DATE
     *
     * @param createDate the value for CUSTOMER.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CREATE_STAFF
     *
     * @return the value of CUSTOMER.CREATE_STAFF
     *
     * @mbggenerated
     */
    public String getCreateStaff() {
        return createStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CREATE_STAFF
     *
     * @param createStaff the value for CUSTOMER.CREATE_STAFF
     *
     * @mbggenerated
     */
    public void setCreateStaff(String createStaff) {
        this.createStaff = createStaff == null ? null : createStaff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_ADDR
     *
     * @return the value of CUSTOMER.CUST_ADDR
     *
     * @mbggenerated
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_ADDR
     *
     * @param custAddr the value for CUSTOMER.CUST_ADDR
     *
     * @mbggenerated
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_AREA_GRADE
     *
     * @return the value of CUSTOMER.CUST_AREA_GRADE
     *
     * @mbggenerated
     */
    public String getCustAreaGrade() {
        return custAreaGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_AREA_GRADE
     *
     * @param custAreaGrade the value for CUSTOMER.CUST_AREA_GRADE
     *
     * @mbggenerated
     */
    public void setCustAreaGrade(String custAreaGrade) {
        this.custAreaGrade = custAreaGrade == null ? null : custAreaGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_AREA_GRADE_PROV
     *
     * @return the value of CUSTOMER.CUST_AREA_GRADE_PROV
     *
     * @mbggenerated
     */
    public String getCustAreaGradeProv() {
        return custAreaGradeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_AREA_GRADE_PROV
     *
     * @param custAreaGradeProv the value for CUSTOMER.CUST_AREA_GRADE_PROV
     *
     * @mbggenerated
     */
    public void setCustAreaGradeProv(String custAreaGradeProv) {
        this.custAreaGradeProv = custAreaGradeProv == null ? null : custAreaGradeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_CONTROL_LEVEL
     *
     * @return the value of CUSTOMER.CUST_CONTROL_LEVEL
     *
     * @mbggenerated
     */
    public String getCustControlLevel() {
        return custControlLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_CONTROL_LEVEL
     *
     * @param custControlLevel the value for CUSTOMER.CUST_CONTROL_LEVEL
     *
     * @mbggenerated
     */
    public void setCustControlLevel(String custControlLevel) {
        this.custControlLevel = custControlLevel == null ? null : custControlLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_NAME
     *
     * @return the value of CUSTOMER.CUST_NAME
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_NAME
     *
     * @param custName the value for CUSTOMER.CUST_NAME
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_NUMBER
     *
     * @return the value of CUSTOMER.CUST_NUMBER
     *
     * @mbggenerated
     */
    public String getCustNumber() {
        return custNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_NUMBER
     *
     * @param custNumber the value for CUSTOMER.CUST_NUMBER
     *
     * @mbggenerated
     */
    public void setCustNumber(String custNumber) {
        this.custNumber = custNumber == null ? null : custNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_ORDER_ID
     *
     * @return the value of CUSTOMER.CUST_ORDER_ID
     *
     * @mbggenerated
     */
    public String getCustOrderId() {
        return custOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_ORDER_ID
     *
     * @param custOrderId the value for CUSTOMER.CUST_ORDER_ID
     *
     * @mbggenerated
     */
    public void setCustOrderId(String custOrderId) {
        this.custOrderId = custOrderId == null ? null : custOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_SOURCE_ID
     *
     * @return the value of CUSTOMER.CUST_SOURCE_ID
     *
     * @mbggenerated
     */
    public String getCustSourceId() {
        return custSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_SOURCE_ID
     *
     * @param custSourceId the value for CUSTOMER.CUST_SOURCE_ID
     *
     * @mbggenerated
     */
    public void setCustSourceId(String custSourceId) {
        this.custSourceId = custSourceId == null ? null : custSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_STATUS_CD
     *
     * @return the value of CUSTOMER.CUST_STATUS_CD
     *
     * @mbggenerated
     */
    public String getCustStatusCd() {
        return custStatusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_STATUS_CD
     *
     * @param custStatusCd the value for CUSTOMER.CUST_STATUS_CD
     *
     * @mbggenerated
     */
    public void setCustStatusCd(String custStatusCd) {
        this.custStatusCd = custStatusCd == null ? null : custStatusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_STATUS_DATE
     *
     * @return the value of CUSTOMER.CUST_STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getCustStatusDate() {
        return custStatusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_STATUS_DATE
     *
     * @param custStatusDate the value for CUSTOMER.CUST_STATUS_DATE
     *
     * @mbggenerated
     */
    public void setCustStatusDate(Date custStatusDate) {
        this.custStatusDate = custStatusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_SUB_TYPE
     *
     * @return the value of CUSTOMER.CUST_SUB_TYPE
     *
     * @mbggenerated
     */
    public String getCustSubType() {
        return custSubType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_SUB_TYPE
     *
     * @param custSubType the value for CUSTOMER.CUST_SUB_TYPE
     *
     * @mbggenerated
     */
    public void setCustSubType(String custSubType) {
        this.custSubType = custSubType == null ? null : custSubType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_SUB_TYPE_PROV
     *
     * @return the value of CUSTOMER.CUST_SUB_TYPE_PROV
     *
     * @mbggenerated
     */
    public String getCustSubTypeProv() {
        return custSubTypeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_SUB_TYPE_PROV
     *
     * @param custSubTypeProv the value for CUSTOMER.CUST_SUB_TYPE_PROV
     *
     * @mbggenerated
     */
    public void setCustSubTypeProv(String custSubTypeProv) {
        this.custSubTypeProv = custSubTypeProv == null ? null : custSubTypeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_TYPE
     *
     * @return the value of CUSTOMER.CUST_TYPE
     *
     * @mbggenerated
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_TYPE
     *
     * @param custType the value for CUSTOMER.CUST_TYPE
     *
     * @mbggenerated
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.CUST_TYPE_PROV
     *
     * @return the value of CUSTOMER.CUST_TYPE_PROV
     *
     * @mbggenerated
     */
    public String getCustTypeProv() {
        return custTypeProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.CUST_TYPE_PROV
     *
     * @param custTypeProv the value for CUSTOMER.CUST_TYPE_PROV
     *
     * @mbggenerated
     */
    public void setCustTypeProv(String custTypeProv) {
        this.custTypeProv = custTypeProv == null ? null : custTypeProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.DISTRIBUTOR_ID
     *
     * @return the value of CUSTOMER.DISTRIBUTOR_ID
     *
     * @mbggenerated
     */
    public String getDistributorId() {
        return distributorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.DISTRIBUTOR_ID
     *
     * @param distributorId the value for CUSTOMER.DISTRIBUTOR_ID
     *
     * @mbggenerated
     */
    public void setDistributorId(String distributorId) {
        this.distributorId = distributorId == null ? null : distributorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.ENTER_DATE
     *
     * @return the value of CUSTOMER.ENTER_DATE
     *
     * @mbggenerated
     */
    public Date getEnterDate() {
        return enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.ENTER_DATE
     *
     * @param enterDate the value for CUSTOMER.ENTER_DATE
     *
     * @mbggenerated
     */
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.EXT_CUST_ID
     *
     * @return the value of CUSTOMER.EXT_CUST_ID
     *
     * @mbggenerated
     */
    public String getExtCustId() {
        return extCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.EXT_CUST_ID
     *
     * @param extCustId the value for CUSTOMER.EXT_CUST_ID
     *
     * @mbggenerated
     */
    public void setExtCustId(String extCustId) {
        this.extCustId = extCustId == null ? null : extCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.INDUSTRY_TYPE_ID
     *
     * @return the value of CUSTOMER.INDUSTRY_TYPE_ID
     *
     * @mbggenerated
     */
    public String getIndustryTypeId() {
        return industryTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.INDUSTRY_TYPE_ID
     *
     * @param industryTypeId the value for CUSTOMER.INDUSTRY_TYPE_ID
     *
     * @mbggenerated
     */
    public void setIndustryTypeId(String industryTypeId) {
        this.industryTypeId = industryTypeId == null ? null : industryTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.IS_INSTEAD
     *
     * @return the value of CUSTOMER.IS_INSTEAD
     *
     * @mbggenerated
     */
    public String getIsInstead() {
        return isInstead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.IS_INSTEAD
     *
     * @param isInstead the value for CUSTOMER.IS_INSTEAD
     *
     * @mbggenerated
     */
    public void setIsInstead(String isInstead) {
        this.isInstead = isInstead == null ? null : isInstead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.IS_REALNAME
     *
     * @return the value of CUSTOMER.IS_REALNAME
     *
     * @mbggenerated
     */
    public String getIsRealname() {
        return isRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.IS_REALNAME
     *
     * @param isRealname the value for CUSTOMER.IS_REALNAME
     *
     * @mbggenerated
     */
    public void setIsRealname(String isRealname) {
        this.isRealname = isRealname == null ? null : isRealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.LAST_ORDER_ITEM_ID
     *
     * @return the value of CUSTOMER.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public String getLastOrderItemId() {
        return lastOrderItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.LAST_ORDER_ITEM_ID
     *
     * @param lastOrderItemId the value for CUSTOMER.LAST_ORDER_ITEM_ID
     *
     * @mbggenerated
     */
    public void setLastOrderItemId(String lastOrderItemId) {
        this.lastOrderItemId = lastOrderItemId == null ? null : lastOrderItemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.PARTY_ID
     *
     * @return the value of CUSTOMER.PARTY_ID
     *
     * @mbggenerated
     */
    public String getPartyId() {
        return partyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.PARTY_ID
     *
     * @param partyId the value for CUSTOMER.PARTY_ID
     *
     * @mbggenerated
     */
    public void setPartyId(String partyId) {
        this.partyId = partyId == null ? null : partyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.REMARK
     *
     * @return the value of CUSTOMER.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.REMARK
     *
     * @param remark the value for CUSTOMER.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.SECRECY_LEV
     *
     * @return the value of CUSTOMER.SECRECY_LEV
     *
     * @mbggenerated
     */
    public String getSecrecyLev() {
        return secrecyLev;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.SECRECY_LEV
     *
     * @param secrecyLev the value for CUSTOMER.SECRECY_LEV
     *
     * @mbggenerated
     */
    public void setSecrecyLev(String secrecyLev) {
        this.secrecyLev = secrecyLev == null ? null : secrecyLev.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.SECRECY_LEV_PROV
     *
     * @return the value of CUSTOMER.SECRECY_LEV_PROV
     *
     * @mbggenerated
     */
    public String getSecrecyLevProv() {
        return secrecyLevProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.SECRECY_LEV_PROV
     *
     * @param secrecyLevProv the value for CUSTOMER.SECRECY_LEV_PROV
     *
     * @mbggenerated
     */
    public void setSecrecyLevProv(String secrecyLevProv) {
        this.secrecyLevProv = secrecyLevProv == null ? null : secrecyLevProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.STATUS_CD
     *
     * @return the value of CUSTOMER.STATUS_CD
     *
     * @mbggenerated
     */
    public String getStatusCd() {
        return statusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.STATUS_CD
     *
     * @param statusCd the value for CUSTOMER.STATUS_CD
     *
     * @mbggenerated
     */
    public void setStatusCd(String statusCd) {
        this.statusCd = statusCd == null ? null : statusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.STATUS_DATE
     *
     * @return the value of CUSTOMER.STATUS_DATE
     *
     * @mbggenerated
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.STATUS_DATE
     *
     * @param statusDate the value for CUSTOMER.STATUS_DATE
     *
     * @mbggenerated
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.UPDATE_DATE
     *
     * @return the value of CUSTOMER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.UPDATE_DATE
     *
     * @param updateDate the value for CUSTOMER.UPDATE_DATE
     *
     * @mbggenerated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CUSTOMER.UPDATE_STAFF
     *
     * @return the value of CUSTOMER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public String getUpdateStaff() {
        return updateStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CUSTOMER.UPDATE_STAFF
     *
     * @param updateStaff the value for CUSTOMER.UPDATE_STAFF
     *
     * @mbggenerated
     */
    public void setUpdateStaff(String updateStaff) {
        this.updateStaff = updateStaff == null ? null : updateStaff.trim();
    }
}